name: gameroom
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  auto_animated: ^3.0.1
  auto_route: 4.0.1
  built_value: ^8.3.2
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.14
  connectivity_plus: ^2.1.0
  credit_card_validator: ^2.0.1
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.0
  easy_mask: ^2.0.1
  email_validator: ^2.0.1
  equatable: ^2.0.3
  firebase_auth: ^3.3.17
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_easyloading: ^3.0.3
  flutter_hooks: ^0.18.1
  flutter_keyboard_visibility: ^5.2.0
  flutter_secure_storage: ^5.0.2
  flutter_native_splash: ^1.3.2
  flutter_screenutil: ^5.0.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.0.0
  fpdart: ^0.0.12
  freezed_annotation: null
  get_it: ^7.2.0
  google_fonts: 2.1.1
  image_picker: ^0.8.4+4
  injectable: ^1.5.3
  logger: ^1.1.0
  octo_image: ^1.0.1
  password_strength: ^0.2.0
  phone_number: ^0.12.0+2
  pin_code_fields: ^7.4.0
  share_plus: ^4.0.4
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.2

dev_dependencies:
  auto_route_generator: null
  build_runner: ^2.1.1
  built_value_generator: ^8.3.2
  flutter_lints: ^1.0.0

  flutter_test:
    sdk: flutter
  freezed: null
  injectable_generator: null

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lang/en.json
    - assets/lang/ru.json
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #